### ISSUE TITLE
Fix type for geo coordinates

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap.prototype#106] opened 2014-04-16 16:05 UTC
Some resources (e.g. [1], from the WSIS data?) contain malform `@type` properties in their geo coordinates. The value should be `http://schema.org/GeoCoordinates` instead of `geo:Coordinates`:

```
{
    @id: "urn:uuid:a0f72732-003c-4363-ac7d-d92e050b740e#!",
    @type: "geo:Coordinates",
    latitude: [
        "38.89511"
    ],
    longitude: [
        "-77.03637"
    ]
}
```

should be

```
{
    @id: "urn:uuid:a0f72732-003c-4363-ac7d-d92e050b740e#!",
    @type: "http://schema.org/GeoCoordinates",
    latitude: [
        "38.89511"
    ],
    longitude: [
        "-77.03637"
    ]
}
```

[1] http://lobid.org/oer/f506dfb9-d1c7-4dd3-99bf-59811dbe4406#!

**Comment by dr0i** [comment] 2014-04-17 08:49
Hm, I don't understand why this is so. In the ntriples the transformation produces it says `<http://schema.org/geoCoordinates>` and i cannot found the reduced form `"geo:Coordinates"` ". @fsteeg do you have a clue ?

**Comment by fsteeg** [comment] 2014-04-17 09:18
I think this is a JSON-LD feature caused by the `geo` mapping in out context document:

http://api.lobid.org/oer/data/context.json

When requested as NTriples the full property is used:

`curl -H "Accept: text/plain" "http://lobid.org/oer/f506dfb9-d1c7-4dd3-99bf-59811dbe4406"`

`<urn:uuid:a0f72732-003c-4363-ac7d-d92e050b740e#!> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/geoCoordinates> .`

@literarymachine Since you don't consume the JSON-LD but an RDF serialization, does this actually cause an issue in the UI?

**Comment by literarymachine** [comment] 2014-04-17 09:43
> @literarymachine Since you don't consume the JSON-LD but an RDF serialization, does this actually cause an issue in the UI?

Idependent of the serialization, the type should be `http://schema.org/GeoCoordinates` (with capital G):

```
<urn:uuid:a0f72732-003c-4363-ac7d-d92e050b740e#!> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/GeoCoordinates> .
```

RDF is case-sensitive.

**Comment by dr0i** [comment] 2014-04-17 10:00
deployed to staging.

**Comment by literarymachine** [comment] 2014-04-17 10:13
Works, and appears to be deployed to production already:

```
$ curl -H "Accept: text/plain" "http://lobid.org/oer/f506dfb9-d1c7-4dd3-99bf-59811dbe4406#\!"| grep GeoCoordinates
<urn:uuid:a0f72732-003c-4363-ac7d-d92e050b740e#!> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/GeoCoordinates> .
```

**Comment by fsteeg** [comment] 2014-04-17 10:16
Thanks for the confirmation, closing.

Also fixed in JSON-LD (with the uppercase `G` it is no longer changed by to `geo` context property), see: 

http://lobid.org/oer/f506dfb9-d1c7-4dd3-99bf-59811dbe4406

**Closed as completed by fsteeg** 2014-04-17 10:16 UTC
Labels: bug, data, 3 - Review
